@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity user {
  **id: SMALLINT <<PK>>**
  --
  email: VARCHAR(64) <<UNIQUE>>
  password: VARCHAR(128)
}

entity event {
  **id: INTEGER <<PK>>**
  --
  name: VARCHAR(64)
  description: TEXT
  graphic: VARCHAR(64)
  start_date: DATE
  end_date: DATE
  category_id: SMALLINT <<FK>>
}

entity category {
  **id: SMALLINT <<PK>>**
  --
  name: VARCHAR(32) <<UNIQUE>>
  color: VARCHAR(7)
  icon_svg: VARCHAR(64)
}




event ||--|| category

@enduml